### ISSUE TITLE
ast: are you mentioning me?

### ISSUE THREAD

**Issue by angelotrabuco2013** [thepegleg/thepegleg.github.io#17]
**hi, i'm ast, the powerful developer.**
i was disappointed. i just took down my fork for being not broken. but, the original fake error page has a link that takes me to the pegleg classroom, which contains the same word that takes me to a page containing a welcome message and a **BUNCH** of links when i click on it. the main page is a fake gh pages 404 error, but it has atlas on it. i clicked on atlas, but it is slightly buggy (*e.g.* the page works fine but it is loading incorrectly). the platform's code has the longest directory name (it was <q>asdjklhfskjafhakfhueoyraehfjkcnjkdscnsjakdreuoiwefh</q>, which is gibberish). the url of the platform is https://thepegleg.github.io/asdjklhfskjafhakfhueoyraehfjkcnjkdscnsjakdreuoiwefh/. the url of the page containing these links is https://thepegleg.github.io/asdjklhfskjafhakfhueoyraehfjkcnjkdscnsjakdreuoiwefh/atlas.html. all of the pages on the not games section have a basic design (which still exists to this day). the basic design on these pages was introduced when html was released in 1993, the year when [mosaic](https://en.wikipedia.org/wiki/Mosaic_(web_browser)) was officially released, but unfortunately, the final version of the browser was 3.0, before being ultimately discontinued in 1997.

also, is there a code to access the hold? without the code, i won't be able to access the hold.

**Comment by sebastian-92** [comment]
Thank you for replying! Yes, I am mentioning you.  The long directory name is to discourage people from accessing all the fun stuff without going through to the about:blank page. The hold code is pegleg1234. If you want to work on thepegleg, I am sending you an invite shortly. Also, what are the bugs in atlas? Thank you again for responding.

**Comment by sebastian-92** [comment]
You have not answered in a while, assuming that you wont
